### PR TITLE
Add custom stylesheets for writing styleguide

### PR DESCRIPTION
**Pull request by geofflambeth**
## To-do items

- Rename repo for more general use
- Hook up the writing style guide to accept our stylesheet
- Get approval and launch

### CODE REVIEW

**Comment by geofflambeth** [comment]
## Updates

- Repo renamed for broad use applying custom styles and assets to pages
- Guide hooked up with our custom sheet, ready for implementation if approved

## Still waiting on 

- Approval

**Comment by geofflambeth** [comment]
@djm653 when you get back we can discuss this, but I've got everything wired up to fix the [heading](https://github.com/UM-Content-Team/Content-Team-Resource-Library/issues/167) and [capitalization](https://github.com/UM-Content-Team/Content-Team-Resource-Library/issues/86) styling issues we've had on the writing style guide. With your approval, merging this pull request would finish connecting a custom stylesheet to all the styleguide pages. We could then turn the styling on and off as needed from here, without manually making edits to each writing styleguide page.

I've included screenshots below, let's discuss when you get back. Hope you're feeling better soon!


## Before demo image

Screen Shot 2022-08-04 at 2 13 54 PM

## After demo image

Screen Shot 2022-08-04 at 2 14 05 PM

Thanks so much!

Best,\
Geoff

**Review by djm653 — APPROVED** [review]
Looks great!!

**Comment by geofflambeth** [comment]
> https://github.com/UM-Content-Team/writing-editing-custom-web-assets/pull/1#pullrequestreview-1063594510

Great @djm653 I've merged this update into the main branch and approved the deployment! If we need to make any changes—or remove them completely—it should now be easy to do all in one place. I've also carefully added some very restricted approval and review requirements to ensure that only you or I can approve a change, and only I can deploy a change. Take a look at the [word list](https://nau.edu/writing-style-guide/word-list/)—it's a good example—and let me know what you think when you have a chance!

Happy Friday :)

**Pull request merged**
